Zadanie4
domini4k/Zadania pull request #1
Opened 2021-06-15 14:03 UTC by domini4k

2021-06-16 14:21 UTC, AdrianDlu requested changes

2021-06-16 14:21 UTC, AdrianDlu commented on force-app/main/default/classes/OfferController.cls
> +public with sharing class OfferController {
jdocki?

2021-06-16 14:21 UTC, AdrianDlu commented on force-app/main/default/classes/OfferController.cls
> +    List<Car_Posting__c> offersPhysical = [
Pobierasz wszystkie oferty z sodowiska a jak ich bedzie 50K+? powinienes pobrac tylko te ktore sa wazne

2021-06-16 14:21 UTC, AdrianDlu commented on force-app/main/default/classes/OfferController.cls
> +  public static void AvoidDuplicates(List<Car_Posting__c> newCarOffers) {
nazwy metod z malej litery

2021-06-16 14:21 UTC, AdrianDlu commented on force-app/main/default/classes/OfferController.cls
> +    List<Vehicle__c> vehicles = [SELECT Id FROM Vehicle__c];
zly select

2021-06-16 14:21 UTC, AdrianDlu commented on force-app/main/default/classes/OfferController.cls
> +        if (carOffer.Vehicle__c == vehicle.Id) {
Moze zamiast fora w forze razem z ifem to lepiej zbudowac sobie mapke

2021-06-16 14:21 UTC, AdrianDlu commented on force-app/main/default/classes/OfferController.cls
> +        newCarOffer.addError('Car is already physically listed in');
hardcode i tu nie powinno byc nazwy salonu?

2021-06-16 14:21 UTC, AdrianDlu commented on force-app/main/default/classes/OfferControllerTest.cls
> +        'Car is already physically listed in',
hardcode

2021-06-16 14:21 UTC, AdrianDlu commented on force-app/main/default/classes/OfferControllerTest.cls
> +private with sharing class OfferControllerTest {
jdocki wszedzie

2021-06-16 14:21 UTC, AdrianDlu commented on force-app/main/default/classes/OfferControllerTest.cls
> +        'Car is already physically listed in',
hardcode

2021-06-16 14:21 UTC, AdrianDlu commented on force-app/main/default/classes/OfferControllerTest.cls
> +}
sporo kodu  sie duplikuje moze mozna go wydzielic do jakiejs metody?

2021-06-16 14:21 UTC, AdrianDlu commented on force-app/main/default/classes/SalonController.cls
> +    List<Salon__c> warehouses = [
bad select

2021-06-16 14:21 UTC, AdrianDlu commented on force-app/main/default/classes/SalonController.cls
> +    List<Account> accs = [SELECT Id FROM Account];
bad select

2021-06-16 14:21 UTC, AdrianDlu commented on force-app/main/default/classes/SalonController.cls
> +          count++;
moze lepiej mapa accountId na integer wtedy select na account nie bedzie potrzebny

2021-06-16 14:21 UTC, AdrianDlu commented on force-app/main/default/classes/SalonController.cls
> +      if (salon.Status__c == 'Closed') {
Tu sprawdzasz czy salon jest zamkniety a nie czy jest zamykany

2021-06-17 09:39 UTC, AdrianDlu requested changes

2021-06-17 09:39 UTC, AdrianDlu commented on force-app/main/default/classes/SalonController.cls
> +    List<Car_Posting__c> carOffers = [SELECT Salon__r.Id FROM Car_Posting__c];
Jaka jest roznica miedzy Salon__r.Id a Salon__c? Bad select

2021-06-17 09:39 UTC, AdrianDlu commented on force-app/main/default/classes/SalonController.cls
> +    List<Vehicle__c> vehicles = [SELECT Salon__c FROM Vehicle__c];
bad select

2021-06-17 09:39 UTC, AdrianDlu commented on force-app/main/default/classes/SalonController.cls
> +    for (Salon__c salon : salons) {
Czy musisz sprawdzac wszystkie salony?

2021-06-17 09:39 UTC, AdrianDlu commented on force-app/main/default/classes/SalonController.cls
> +      for (Vehicle__c vehicle : vehicles) {
moze mapka

2021-06-17 09:39 UTC, AdrianDlu commented on force-app/main/default/classes/SalonControllerTest.cls
> +}
Zastanow sie nad stworzeniem TestDataFactory klasy do preparowania danych dla testow

2021-06-17 09:39 UTC, AdrianDlu commented on force-app/main/default/classes/VehicleController.cls
> +    List<Telemetry__c> data = [SELECT Vehicle__c FROM Telemetry__c];
bad select

2021-06-17 09:39 UTC, AdrianDlu commented on force-app/main/default/classes/VehicleController.cls
> +    List<Vehicle__c> vehiclesAll = [SELECT Salon__c FROM Vehicle__c];
bad selects

2021-06-18 13:18 UTC, AdrianDlu requested changes

2021-06-18 13:18 UTC, AdrianDlu commented on force-app/main/default/classes/OfferController.cls
> +        newCarOffer.addError('Car is already physically listed');
hardcode zamien na constanta

2021-06-18 13:18 UTC, AdrianDlu commented on force-app/main/default/classes/OfferController.cls
> +      if (numberOfCarOffers.get(newCarOffer.Vehicle__c) > 1) {
&&  !newCarOffer.Virtual__c

2021-06-18 13:18 UTC, AdrianDlu commented on force-app/main/default/classes/SalonController.cls
> +      if (salon.Warehouse__c == true) {
Wystarczy salon.Warehouse__c

2021-06-18 13:18 UTC, AdrianDlu commented on force-app/main/default/classes/SalonController.cls
> +      if (numberOfWarehouses.get(warehouse.Account__c) > 1) {
&& salon.Warehouse__c

2021-06-18 13:18 UTC, AdrianDlu commented on force-app/main/default/classes/SalonController.cls
> +          'There can be only one warehouse related to specific account'
hardcode

2021-06-18 13:18 UTC, AdrianDlu commented on force-app/main/default/classes/SalonController.cls
> +    List<Salon__c> warehouses = [
te magazyny tez lepiej by bylo pewnie pobrac tylko dla zamykanych salonow. Czyli ta logike moze przeniesc ponizej tej z lini 80

2021-06-18 13:18 UTC, AdrianDlu commented on force-app/main/default/classes/SalonController.cls
> +        salon.addError('There are more vehicles than desired parking spots');
hardcodes

2021-06-18 13:18 UTC, AdrianDlu commented on force-app/main/default/classes/SalonController.cls
> +    List<Vehicle__c> vehicles = [
Chyba z wszystkich salonow powinismy wybrac tylko te ktorym liczba miejsc zostala zmniejszona

2021-06-18 13:18 UTC, AdrianDlu commented on force-app/main/default/classes/VehicleController.cls
> +    for (Telemetry__c telemetry : data) {
po co ta logika? z jednej mapy przekladasz do drugej

2021-06-18 13:18 UTC, AdrianDlu commented on force-app/main/default/classes/VehicleController.cls
> +          if (vehicle.Salon__c == salon.Id) {
mapa salonId na liste pojazdow moze troche usprawnic tego fora w forze

2021-06-18 13:18 UTC, AdrianDlu commented on force-app/main/default/classes/VehicleController.cls
> +              'There are not enough parking spots for vehicles in this salon ' +
hardcode

2021-06-20 20:06 UTC, domini4k commented on force-app/main/default/classes/SalonController.cls
> +      if (numberOfWarehouses.get(warehouse.Account__c) > 1) {
Wydaję mi się, że w tym wypadku nie jest to konieczne, bo iteruję po liście zawierającej tylko warehousy. Ale mogę też czegoś nie dostrzegać

2021-06-22 04:54 UTC, AdrianDlu requested changes

2021-06-22 04:54 UTC, AdrianDlu commented on force-app/main/default/triggers/CarOffer.trigger
> +  OfferController.AvoidDuplicates(Trigger.new);
nazy metod z malej litery

2021-06-22 04:54 UTC, AdrianDlu commented on force-app/main/default/classes/Constant.cls
> +  public static final String offerControllerErrorMessage = 'Car is already physically listed';
Na przyszlosc stale pisze sie UPPER_CASEM czli np. OFFER_CONTROLLER_ERROR_MESSAGE

2021-06-22 04:54 UTC, AdrianDlu commented on force-app/main/default/classes/SalonController.cls
> +        salon.Status__c == 'Closed'
hardcode

2021-06-22 04:54 UTC, AdrianDlu commented on force-app/main/default/classes/TestDataFactory.cls
> +  public static List<Account> Accounts(Integer j) {
bad variable name inAmmount zamiast j :)

2021-06-22 04:54 UTC, AdrianDlu commented on force-app/main/default/classes/TestDataFactory.cls
> +    Integer j,
Nazwy zmiennych

2021-06-22 04:56 UTC, AdrianDlu commented on force-app/main/default/classes/OfferControllerTest.cls
> +    String mssg = 'Car is already physically listed';
uzyj constanta

2021-06-22 10:17 UTC, AdrianDlu approved these changes

2021-06-22 10:17 UTC, merged